### ISSUE TITLE
Properties of the first "title" slide

### ISSUE THREAD

**Issue by fradav** [kinjo/org-impress-js.el#10]
Hi,

It would be nice if we could set the properties of the first "title" slide (data-/rotate-) etc., not just the TOC slide

Regards

**Comment by kinjo** [comment]
@fradav I didn't notice it, thank you:-) I'll consider what to do about that this week.

**Comment by kinjo** [comment]
@fradav Okay, I have just added a new export option `IMPRESSJS_TITLE`. More details and concrete example are described in README.org. I hope you like it.

**Comment by fradav** [comment]
Just tested, it works great, thanks you very much!
