### ISSUE TITLE
org-impress-js-headline: Symbol's function definition is void: org-html-format-headline--wrap

### ISSUE THREAD

**Issue by nblumoe** [kinjo/org-impress-js.el#7]
When trying to export I get the above error message. This seems to be an issue with changed function names in ox-html. The same thing happened (and is still happening for me) on ox-reveal:
http://lists.gnu.org/archive/html/emacs-orgmode/2014-08/msg00328.html

My Versions:
Org-mode version 8.3beta (release_8.3beta-797-ga5c456 @ [...])
GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2014-10-21 on builder10-9.porkrind.org
Mac OSX 10.10.2

**Comment by nblumoe** [comment]
@kinjo any ideas?

**Comment by kinjo** [comment]
@nblumoe It seems that the issue is due to the version of Org-mode. I'll try this issue in this weekend.

**Comment by kinjo** [comment]
@nblumoe I just finished the fix. Could you please try it out?

**Comment by nblumoe** [comment]
Thanks, fixed! :+1:
