### ISSUE TITLE
8.3 org-mode REAL version number

### ISSUE THREAD

**Issue by fradav** [kinjo/org-impress-js.el#9]
Hi,

You said in the README that you tested on Org-mode version 8.3beta(release_8.3beta-891-g9e3c3e) , but can you give the exact tag/commit or version of the org-mode ? "891-g9e3c3e" doesn't match anything in the org-mod log, and your code doesn't work with the latest org-mode (30/03)

Regards,

**Comment by kinjo** [comment]
@fradav Thank you for letting me know! I'll fix it as soon as possible.

**Comment by kinjo** [comment]
That reminds me, I also need to write a test....

**Comment by kinjo** [comment]
@fradav Hi, I fix this problem right now. Could you please try it out? I made sure that ox-impress-js.el works fine with Org version 8.3beta in master branch(commit cff54cd) and then explicitly show supported commit number of Org in README.

**Comment by fradav** [comment]
It works now, thanks you very much!
